blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDelete

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', cache_page(60)(BlogListView.as_view()), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDelete.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('', include('contacts.urls')),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, set_new_password, \
    UserConfirmEmailView, \
    UserConfirmedView, password_reset, UserConfirmationSentView

app_name = "users"

urlpatterns = [

    path("", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("registration/", RegisterView.as_view(), name="registration"),
    path('email_confirmation_sent/', UserConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmedView.as_view(), name='email_confirmed'),
    path("profile/", UserUpdateView.as_view(), name="profile"),
    path("profile/set_password", set_new_password, name="set_password"),
    path('password_reset/', password_reset, name='password_reset'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    """Модель для пользователя"""

    username = None

    email = models.EmailField(unique=True, verbose_name='почта')
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm, SetPasswordForm
from users.models import User
from catalog.forms import StyleFormMixin
from django import forms


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ["email", "phone", "country", "avatar", "password1", "password2"]


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ["email", "password", "first_name", "last_name", "phone", "country", "avatar"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class PasswordForm(StyleFormMixin, forms.Form):
    new_password = forms.CharField(label='Новый пароль', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='Подтвердите пароль', widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')

        if new_password and confirm_password and new_password != confirm_password:
            raise forms.ValidationError('Пароли не совпадают')

        return cleaned_data

users/views.py
import random

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView as BaseLoginView, PasswordResetDoneView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, UpdateView, TemplateView
from django.urls import reverse_lazy, reverse

from catalog.services import send_email
from users.forms import UserRegisterForm, UserProfileForm, PasswordForm
from users.models import User
from django.shortcuts import redirect, render
from django.contrib.auth import login


class LoginView(BaseLoginView):
    """Вход на сайт"""

    template_name = "users/login.html"
    title = "Login"


class LogoutView(BaseLogoutView):
    """Выход с сайта"""

    template_name = "users/login.html"


class RegisterView(CreateView):
    """Регистрация нового пользователя и отправка подтверждения на его email"""

    form_class = UserRegisterForm
    template_name = "users/registration/registration_form.html"
    success_url = reverse_lazy('users:registration_reset')
    title = "Регистрация нового пользователя"

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        user.save()
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('users:confirm_email', kwargs={'uidb64': uid, 'token': token})
        current_site = '127.0.0.1:8000'

        subject = 'Подтверждение адреса электронной почты'
        message = (f"Для подтверждения адреса электронной почты"
                   f"перейдите по ссылке: http://{current_site}{activation_url}")
        recipient_list = [user.email]

        # передаем сервисной функции переменные для отправки email пользователю
        # со ссылкой для подтверждения почты
        send_email(subject, message, recipient_list)

        return redirect('users:email_confirmation_sent')


class UserConfirmationSentView(PasswordResetDoneView):
    """Успешный первый этап регистрации"""

    template_name = "users/registration/registration_sent_done.html"


class UserConfirmEmailView(View):
    """Пользователь подтверждает свою регистрацию"""

    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)

            return redirect('users:email_confirmed')
        else:
            return redirect('users:email_confirmation_failed')


class UserConfirmedView(TemplateView):
    """Регистрация пользователя завершена, вывод информации об этом"""

    template_name = 'users/registration/registration_confirmed.html'
    title = "Your email is activated."


class UserUpdateView(LoginRequiredMixin, UpdateView):
    """Профиль пользователя """

    model = User
    success_url = reverse_lazy("catalog:list")
    form_class = UserProfileForm
    template_name = "users/profile.html"

    def get_object(self, queryset=None):
        return self.request.user


@login_required
def set_new_password(request):
    """Установить новый пароль, введенный пользователем в его профиле"""

    if request.method == 'POST':
        form = PasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data['new_password']

            subject = 'Смена пароля вашего профиля на сайте'
            message = f"Пароль успешно изменен.\nВаш новый пароль: {new_password}"
            recipient_list = [request.user.email]

            # передаем сервисной функции переменные для отправки email с новым паролем
            send_email(subject, message, recipient_list)

            request.user.set_password(new_password)
            request.user.save()

            return redirect(reverse("catalog:list"))
    else:
        form = PasswordForm()

    return render(request, 'users/change_password.html', {'form': form})


def password_reset(request):
    """
    Сгенерировать новый пароль пользователя при входе на сайт, если забыли пароль
    """

    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            user = User.objects.get(email=email)
            new_password = "".join([str(random.randint(0, 9)) for _ in range(12)])
            user.set_password(new_password)
            user.save()

            subject = "Сброс пароля на сайте"
            message = f"Пароль успешно сброшен.\nВаш новый пароль: {new_password}"
            recipient_list = [user.email]

            # передаем сервисной функции переменные для отправки email с новым паролем
            send_email(subject, message, recipient_list)

            return redirect(reverse("users:login"))  # Перенаправление на страницу входа

        except User.DoesNotExist:

            return render(request, 'users/registration/password_reset_form.html',
                          {'error_message': 'User not found'})  # Отображение формы с сообщением об ошибке

    return render(request, 'users/registration/password_reset_form.html')  # Вывод формы для ввода email

users/templates/users/change_password.html
{% extends 'catalog/base.html' %}
{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h3>Установите ваш новый пароль</h3><br><br>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Изменить пароль</button>
    </form>

{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h3>Войдите на сайт, используя вашу почту и пароль</h3><br><br>
</div>
<div class="row">
    <div class="row">
        <div class="col-3">
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <p>
                            <button type="submit" class="btn btn-success">Войти</button>
                        </p>
                        <a href="{% url 'users:password_reset' %}" class="p-2 btn btn-warning">Забыл пароль</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends 'catalog/base.html' %}
{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h3>Здесь вы можете внести изменения в свой профиль</h3><br><br>
    </div>
    <div class="row">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header"></div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <p>
                                <button type="submit" class="btn btn-success">Сохранить</button>
                            </p>
                            <a href="{% url 'users:set_password' %}" class="btn btn-success">Установить новый
                                пароль</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}