blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDelete

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', cache_page(60)(BlogListView.as_view()), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDelete.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ProductDetailView, ProductListView, ProductCreateView, ProductUpdateView, ProductDelete, \
    CategoryProductListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('products/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='view'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>/', ProductDelete.as_view(), name='delete_product'),
    path('category/<int:category_pk>', CategoryProductListView.as_view(), name='product_category'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('', include('contacts.urls')),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path

from contacts.views import ContactListView
from contacts.apps import ContactsConfig

app_name = ContactsConfig.name

urlpatterns = [
    path('contacts/', ContactListView.as_view(), name='contacts'),
]

users/urls.py
from django.urls import path
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, set_new_password, \
    UserConfirmEmailView, \
    UserConfirmedView, password_reset, UserConfirmationSentView

app_name = "users"

urlpatterns = [

    path("", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("registration/", RegisterView.as_view(), name="registration"),
    path('email_confirmation_sent/', UserConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmedView.as_view(), name='email_confirmed'),
    path("profile/", UserUpdateView.as_view(), name="profile"),
    path("profile/set_password", set_new_password, name="set_password"),
    path('password_reset/', password_reset, name='password_reset'),
]

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    """Создание модели - полей категорий в таблице БД"""

    name = models.CharField(max_length=100, verbose_name='название')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return f'{self.name}, {self.description}'

    class Meta:
        """Представление написания заголовков в админке"""

        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ('name',)


class Product(models.Model):
    """Создание модели - полей продуктов в таблице БД"""

    # Статусы продуктов
    STATUS_CREATED = 'created'
    STATUS_MODERATED = 'moderated'
    STATUS_PUBLISHED = 'published'
    STATUSES = (
        (STATUS_CREATED, 'добавлен'),
        (STATUS_MODERATED, 'на модерации'),
        (STATUS_PUBLISHED, 'опубликован')
    )

    name = models.CharField(max_length=100, verbose_name='название')
    description = models.TextField(verbose_name='описание')
    preview = models.ImageField(upload_to='products/', default='products/no_image.jpg', verbose_name='изображение',
                                **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория',
                                 related_name='products')
    price = models.IntegerField(verbose_name='цена')
    creation_date = models.DateTimeField(verbose_name='дата создания')
    change_date = models.DateTimeField(verbose_name='дата последнего изменения')
    # Зависимость от владельца продукта
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец', **NULLABLE)
    # Поле текущего статуса продукта
    status = models.CharField(max_length=20, choices=STATUSES, default=STATUS_MODERATED, verbose_name='статус')

    def __str__(self):
        return f'{self.name}, {self.category}, {self.price}'

    class Meta:
        """Представление написания заголовков в админке"""

        verbose_name = "товар"
        verbose_name_plural = "товары"
        permissions = [
            ('set_product_status', 'Can change the status of products'),
            ('change_product_description', 'Can change product description'),
            ('change_product_category', 'Can change product category'),
        ]


class Version(models.Model):
    """Создание модели - полей версии продукта в таблице БД"""

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.CharField(max_length=100, verbose_name='номер версии')
    version_name = models.CharField(max_length=100, verbose_name='название версии')
    is_current_version = models.BooleanField(default=False, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.product}, {self.version_name}, {self.version_number}'

    class Meta:
        """Представление написания заголовков в админке"""

        verbose_name = "версия"
        verbose_name_plural = "версии"

contacts/models.py
from django.db import models


class Contact(models.Model):
    """Создание модели - полей контактов в таблице БД"""

    name = models.CharField(max_length=100, verbose_name='имя')
    email = models.EmailField(max_length=100, verbose_name='email')
    phone = models.CharField(max_length=20, verbose_name='телефон')
    address = models.CharField(max_length=200, verbose_name='адрес')

    def __str__(self):
        return f'{self.name}, {self.email}, {self.phone}, {self.address}'

    class Meta:
        """Представление написания заголовков в админке"""

        verbose_name = "контакт"
        verbose_name_plural = "контакты"

catalog/forms.py
from django import forms

from catalog.models import Product, Version

# Список запрещенных слов, проверяемых при заполнении формы
FORBIDDEN_WORDS = ['казино', 'криптовалюта', 'крипта',
                   'биржа', 'дешево', 'бесплатно', 'обман',
                   'полиция', 'радар'
                   ]


class StyleFormMixin:
    """Класс-миксин для стилизации форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "is_current_version":
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    """Класс для генерации формы создания продукта"""

    class Meta:
        model = Product
        exclude = ('owner', 'status',)

    def clean(self):
        """Метод для валидации полей названия и описания продукта"""

        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        description = cleaned_data.get('description')

        if name and any(word in name.lower() for word in FORBIDDEN_WORDS):
            self.add_error('name', 'Недопустимое слово в названии продукта!')

        if description and any(word in description.lower() for word in FORBIDDEN_WORDS):
            self.add_error('description', 'Недопустимое слово в описании продукта!')

        return cleaned_data


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    """Класс для генерации формы модератора"""

    class Meta:
        model = Product
        fields = ('description', 'category', 'status',)


class VersionForm(StyleFormMixin, forms.ModelForm):
    """Класс для генерации формы версии продукта"""

    class Meta:
        model = Version
        fields = "__all__"

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version
from catalog.services import get_category_by_pk, get_categories


class ProductListView(ListView):
    """Контроллер для главной страницы со списком товаров"""

    model = Product

    def get_context_data(self, **kwargs):
        """Выводим в общий список информацию об активных версиях продукта"""

        context = super().get_context_data(**kwargs)

        categories = get_categories()
        context['categories_list'] = categories

        for product in context['object_list']:
            active_version = product.version_set.filter(is_current_version=True).first()
            if active_version:
                product.active_version_number = active_version.version_number
                product.active_version_name = active_version.version_name
            else:
                product.active_version_number = None
                product.active_version_name = None

        return context

    def get_queryset(self):
        """Выводим информацию согласно правам доступа"""

        user = self.request.user

        # Если пользователь аутентифицирован (в том числе владелец товара)
        if user.is_authenticated:

            # Для администраторов показываем все продукты
            if user.is_staff or user.is_superuser:
                queryset = super().get_queryset()

            # Для остальных аутентифицированных пользователей
            else:
                queryset = super().get_queryset().filter(
                    status=Product.STATUS_PUBLISHED
                )
        else:
            # Для неаутентифицированных пользователей
            queryset = super().get_queryset().filter(
                status=Product.STATUS_PUBLISHED
            )

        return queryset


class CategoryProductListView(ProductListView):
    '''
    Класс для отображения продуктов на главной странице по категориям
    '''

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        category = get_category_by_pk(self.kwargs.get('category_pk'))
        queryset = queryset.filter(category=category)

        return queryset


class ProductDetailView(DetailView):
    """Контроллер для страницы с описанием товара"""

    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    """Контроллер для создания нового товара"""

    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin, UpdateView):
    """Контроллер для редактирования товара"""

    model = Product
    form_class = ProductModeratorForm
    success_url = reverse_lazy('catalog:list')
    permission_required = 'catalog.change_product'

    def test_func(self):
        user = self.request.user
        product = self.get_object()

        if product.owner == user or user.is_staff:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('catalog:list'))

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset

        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDelete(LoginRequiredMixin, DeleteView):
    """Контроллер для удаления продукта"""

    model = Product
    success_url = reverse_lazy('catalog:list')

contacts/views.py
from django.views.generic import ListView
from contacts.models import Contact


class ContactListView(ListView):
    """Контроллер для страницы контактов со списком контактов из БД"""

    model = Contact

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:list' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'contacts:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Блог</a>
    </nav>
    <nav class="m-sm-auto">
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-success" href="{% url 'users:logout' %}">Выйти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Мой профиль</a>
        {% else %}
        <a class="p-2 btn btn-success" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-warning" href="{% url 'users:registration' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

<div class="container">
    <div class="container">
        {% if user.is_authenticated %}
        <h6 align="right">Вы вошли как: {{ user.email }}</h6>
        {% endif %}

        {% block content %}
        {% endblock %}

    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">© {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'contacts:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>USA</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>91-1144442</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>Redmond,WA,98052-6399</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                               required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone"
                               placeholder="Контактный телефон" required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea type="text" name="message" class="form-control" id="message"
                                  placeholder="Ваше сообщение" required></textarea>
                    </div>
                    <input type="submit" value="Отправить">
                </form>
            </div>
        </div>
    </div>

    <div class="col-lg-9 col-md-6 col-sm-12">
        <h3>Контакты из БД:</h3>

        {% for contact in contacts %}
        <h5>ID контакта: {{ contact.id }}</h5>
        <p>Имя: {{ contact.name }}</p>
        <p>E-mail: {{ contact.email }}</p>
        <p>Телефон: {{ contact.phone }}</p>
        <p>Адрес: {{ contact.address }}</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/description.html
{% extends 'catalog/base.html' %}
{% block content %}
{% include 'catalog/includes/inc_description_header.html' %}
<div class="row mx-2">
    <div class="col-md-4 mb-3">
        {% load media_tags %}
        <img src="{% mediapath product.preview %}" class="img-fluid" alt="{{ product.name }}">
    </div>
    <div class="col-md-8 mb-3">
        <h2>{{ product.name }}</h2>
        <p>{{ product.description }}</p>
        <h3>{{ product.price }} руб.</h3><br>
        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
    </div>
</div><br><br>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% block content %}
{% include 'catalog/includes/inc_index_header.html' %}
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for product in products %}
    <div class="col">
        <div class="card h-100">
            <div class="card-header">
                <h3 class="my-0 font-weight-normal">{{ product.name }}</h3>
            </div>
            <div class="card-body d-flex flex-column">
                <h4 class="card-title pricing-card-title">{{ product.price }} руб.</h4>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3 flex-grow-1">
                    <li>{{ product.description|slice:":100" }}</li>
                </ul>
                <div class="d-flex flex-column">
                    <a href="/products/{{ product.id }}/">Подробнее</a><br>
                    <button type="button" class="btn btn-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    <p>Нет товаров</p>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="card-title">
    <h3 class="card-title">
        Удаление товара
    </h3>
</div>
<div class="row">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    </div>
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>Хотите удалить продукт "{{ product.name }}"?</p>
                    <button type="submit" class="btn btn-success">Подтвердить</button>
                    <a href="{% url 'catalog:view' object.pk %}" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
    {% include 'catalog/includes/inc_description_header.html' %}
    <div class="row mx-2">
        <div class="col-md-4 mb-3">
            {% load media_tags %}
            <img src="{% mediapath product.preview %}" class="img-fluid" alt="{{ product.name }}">
        </div>
        <div class="col-md-8 mb-3">
            <h2>{{ product.name }}</h2>
            <p>{{ product.description }}</p>
            <h3>{{ product.price }} руб.</h3><br>
            <div class="d-flex justify-content-between align-items-center">
                {% if perms.catalog.change_product %}
                    <div class="btn-group">
                        <a href="{% url 'catalog:update_product' object.pk %}"
                           class="btn btn-sm btn-outline-secondary">Редактировать</a>
                        <a href="{% url 'catalog:delete_product' object.pk %}"
                           class="btn btn-sm btn-outline-danger">Удалить</a>
                    </div>
                {% endif %}
            </div>
            <div class="col-12 mb-5"><br><br>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
            </div>
        </div>
    </div><br><br>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-title">
                            {% if object %}
                            Редактирование товара
                            {% else %}
                            Добавление товара
                            {% endif %}
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-title">
                            {% if object %}
                            Версии продуктов
                            {% endif %}
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% if not forloop.last %}
                    <hr class="mb-4">
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}
    {% include 'catalog/includes/inc_index_header.html' %}

    <div>
        <br>
        <p>Отсортировать товары по их категориям</p>
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item"><a class="btn btn-dark" href="{% url 'catalog:list' %}">Все</a></li>
            {% for category in categories_list %}
                <li class="list-group-item"><a class="btn btn-outline-dark"
                                               href="{% url 'catalog:product_category' category.pk %}">
                    {{ category.name }}</a></li>
            {% endfor %}
        </ul>
        <hr>
        <br>
    </div>

    <div class="col-12 mb-5">
        {% if user.is_authenticated %}
            <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войдите для добавления продукта</a>
        {% endif %}
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for product in object_list %}
            <div class="col">
                <div class="card h-100">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">{{ product.name }}</h3>
                        {% if product.active_version_number %}
                            <p>Активная версия: {{ product.active_version_number }}<br>
                                {{ product.active_version_name }}</p>
                        {% endif %}
                    </div>
                    <div class="card-body d-flex flex-column">
                        <h4 class="card-title pricing-card-title">{{ product.price }} руб.</h4>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3 flex-grow-1">
                            <li>{{ product.description|slice:":100" }}</li>
                        </ul>
                        <h6 class="card-title pricing-card-title">
                            Создатель: {{ product.owner|default:"отсутствует" }}</h6>
                        <br>
                        <div class="d-flex flex-column">
                            {% if request.user == product.owner %}
                                <a href="/products/{{ product.id }}/">Подробнее</a><br>
                                <button type="button" class="btn btn-primary">Купить</button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Нет товаров</p>
        {% endfor %}
    </div>

{% endblock %}